---
title: "Health Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)

data<-read.csv("C:/Users/KUSHIKA/Desktop/dashboard/blood.csv")

```

row
-----

### histogram of age distribution
```{r}
# histogram of age distribution
ggplot(data, aes(x = Age)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(title = "Age Distribution", x = "Age", y = "Frequency")
```


### pie chart of gender distribution
```{r}
# pie chart of gender distribution
ggplot(data, aes(x = "", fill = Gender)) +
  geom_bar(width = 1) +
  coord_polar(theta = "y") +
  labs(title = "Gender Distribution")
```

row
----

### scatter plot of BMI vs. Cholesterol
```{r}
# scatter plot of BMI vs. Cholesterol
ggplot(data, aes(x = BMI, y = Chol)) +
  geom_point(color = "blue") +
  labs(title = "BMI vs. Cholesterol", x = "BMI", y = "Cholesterol")
```

### bar chart of diagnosis
```{r}
# bar chart of diagnosis
ggplot(data, aes(x = factor(Diagnosis), fill = factor(Diagnosis))) +
  geom_bar() +
  labs(title = "Diagnosis Distribution", x = "Diagnosis", y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```